### ISSUE TITLE
Base runtime implementation on ruby-stones?

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/projectional-gobstones#1]
We already have a pure implementation of a Gobstone`s model: http://githib.com/uqbar-project/ruby-stones.

Perhaps you could use it as inspiration, or even better, as implementation for you Gobstones runtime - through jruby.

**Comment by AlvarezAriel** [comment]
This editor could easily generate ruby code as output, so what you suggest is certainly possible (and quite desirable)

**Comment by AlvarezAriel** [comment]
This was implemented on mps projectional java for simplicity and integration with the tool.
The ruby code generation can still be made on a separate plugin; so I'm closing this for now.
